name: wine-quality-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas>=1.5.0
      - numpy>=1.23.0
      - scikit-learn>=1.2.0
      - mlflow>=2.8.0
      - dagshub>=0.3.0
      - optuna>=3.4.0
      - matplotlib>=3.6.0
      - seaborn>=0.12.0
      - joblib>=1.2.0
      - gunicorn>=21.0.0
      - flask>=2.3.0
